=== khanalAjit/GiftcardShop-XML/catalog_20048817.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
<!-- using vanetican blind style for the css-->


<xs:complexType name="logoType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="of" type="xs:string"  use="required"/>
      </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:complexType name="contact_infoType">
    <xs:sequence>
      <xs:element name="website" type="xs:anyURI"/>
      <xs:element name="address" type="xs:string"/>
      <xs:element name="mobile_phone" type="xs:positiveInteger" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="telephone" type="xs:positiveInteger" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
  </xs:complexType>

<xs:complexType name="middlefType">
    <xs:sequence>
      <xs:element name="store_name" type="xs:string" />
      <xs:element name="contact_info" type="contact_infoType" />
    </xs:sequence>
</xs:complexType>


<xs:complexType name="facebookType" mixed="true">
    <xs:sequence>
      <xs:element name="flogo"  minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="instagramType" mixed="true">
    <xs:sequence>
      <xs:element name="ilogo"  minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="twitterType" mixed="true">
    <xs:sequence>
      <xs:element name="tlogo" minOccurs="0" maxOccurs="1"/>
    </xs:sequence>
  </xs:complexType>


<xs:complexType name="social_mediasType" mixed="true">
    <xs:sequence>
        <xs:element name="facebook" type="facebookType" minOccurs="0" maxOccurs="1"/>
        <xs:element name="instagram" type="instagramType" minOccurs="0" maxOccurs="1"/>
        <xs:element name="twitter" type="twitterType" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
</xs:complexType>



<xs:complexType name="rightfType">
    <xs:sequence>
      <xs:element name="social_medias" type="social_mediasType" />
    </xs:sequence>
</xs:complexType>

<xs:complexType name="headingType">
    <xs:sequence>
      <xs:element name="logo" type="logoType" />
      <xs:element name="middlef" type="middlefType" />
      <xs:element name="rightf" type="rightfType" />
    </xs:sequence>
</xs:complexType>

<xs:complexType name="imageType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="name" type="xs:string"  use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

<xs:complexType name="fleftType">
    <xs:sequence>
      <xs:element name="image" type="imageType" />
      <xs:element name="name" type="xs:string" />
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="costType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="currency" type="xs:string"  use="required"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>

  <!-- this schema defines that the element named discount should have a string data 
    with an attribute which also uses string data and is optional.-->
  <xs:complexType name="discountType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="specialEvent" type="xs:string"  use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>


  <xs:complexType name="shipping_chargeType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="facility" type="xs:string" use="optional"/>
      </xs:extension>
    </xs:simpleContent>
  </xs:complexType>


<xs:complexType name="frightType">
    <xs:sequence>
      <xs:element name="type" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="country" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="code_number" type="xs:string"  minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="cost" type="costType" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="availability" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="validity" type="xs:string"  minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="discount" type="discountType"  minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="quantity" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="shipping_charge" type="shipping_chargeType"  minOccurs="0" maxOccurs="1"/>
      <xs:element name="description" type="xs:string" minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>


<xs:complexType name="designType">
    <xs:sequence>
      <xs:element name="fleft" type="fleftType" />
      <xs:element name="fright" type="frightType" />
    </xs:sequence>
</xs:complexType>


<xs:complexType name="commentsType">
    <xs:simpleContent>
      <xs:extension base="xs:string">
        <xs:attribute name="cmntBy" type="xs:ID"  use="required"/>
      </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:complexType name="reviewsType" mixed="true">
    <xs:sequence>
      <xs:element name="recommendations" type="xs:string"  minOccurs="0"/>
      <xs:element name="rating" type="xs:string"  minOccurs="0"/>
      <xs:element name="comments" type="commentsType"  maxOccurs="unbounded" minOccurs="0"/>
    </xs:sequence>
</xs:complexType>



<xs:complexType name="card_sizeType">
    <xs:sequence>
      <xs:element name="dimention" type="xs:string" />
      <xs:element name="weight" type="xs:string" />
    </xs:sequence>
    <xs:attribute name="cardType" type="xs:string"  use="required"/>
</xs:complexType>


<!-- mixed = 'true' defines that the element contains both PCData and element.-->

<xs:complexType name="product_detailsType" mixed="true">
    <xs:all>
      <xs:element name="card_size" type="card_sizeType" />
      <xs:element name="manufacturer" type="xs:string" />
      <xs:element name="selling_rank" type="xs:string" />
    </xs:all>
</xs:complexType>

<!-- type attribute should only have two values i.e., physical and digital.-->
<xs:simpleType name="typeType">
  <xs:restriction base="xs:string">
    <xs:enumeration value="physical"/>
    <xs:enumeration value="digital"/>
  </xs:restriction>
</xs:simpleType>

<xs:complexType name="cardType">
    <xs:sequence>
      <xs:element name="design" type="designType" />
      <xs:element name="reviews" type="reviewsType"  minOccurs="0" maxOccurs="unbounded"/>
      <xs:element name="product_details" type="product_detailsType"  minOccurs="0" maxOccurs="unbounded"/>
    </xs:sequence>
    <!-- use defines the requirement of the attribute.
    tje type attribute has restriction so the data type is not given in this statement.-->
    <xs:attribute name="CID" type="xs:ID"  use="required"/>
    <xs:attribute name="type" type="typeType"  use="required"/>
  </xs:complexType>


<!-- the element 'card' can exist zero or more times.-->
  
<xs:complexType name="giftcardsType">
        <xs:sequence>
          <xs:element name="card" type="cardType"  maxOccurs="unbounded" minOccurs="0"/>
        </xs:sequence>
</xs:complexType>




<!-- logoType is already defined above -->
<xs:complexType name="amazonType" mixed="true">
    <xs:sequence>
      <xs:element name="logo" type="logoType" />
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="kalyanType" mixed="true">
    <xs:sequence>
      <xs:element name="logo" type="logoType" />
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="lifestyleType" mixed="true">
    <xs:sequence>
      <xs:element name="logo" type="logoType" />
    </xs:sequence>
  </xs:complexType>


  <xs:complexType name="itunesType" mixed="true">
    <xs:sequence>
      <xs:element name="logo" type="logoType" />
    </xs:sequence>
  </xs:complexType>


  <!-- min ouccurs and max occurs defines the apperance of the element in XML document
  here, these elements should not exist more than once in the XML document.-->
<xs:complexType name="endingType" mixed="true">
    <xs:sequence>
      <xs:element name="amazon" type="amazonType" maxOccurs="1" minOccurs="0"/>
      <xs:element name="kalyan" type="kalyanType" maxOccurs="1" minOccurs="0"/>
      <xs:element name="lifestyle" type="lifestyleType" maxOccurs="1" minOccurs="0"/>
      <xs:element name="itunes" type="itunesType" maxOccurs="1" minOccurs="0"/>
    </xs:sequence>
  </xs:complexType>


<xs:complexType name="ajstoreType">
    <xs:sequence>
        <xs:element name="heading"  type="headingType"/>
        <xs:element name="welcome"  type="xs:string"/>
        <xs:element name="giftcards"   type="giftcardsType"/>
        <xs:element name="ending"   type="endingType"/>
    </xs:sequence>
</xs:complexType>

<!-- every complex type element is given a different 
  eg 'ajstoreType is given to ajstore element as it is a complex element'
Those element should be defined so, they are generally defined above the element declaration.-->
<xs:element name="ajstore"  type="ajstoreType"/>
</xs:schema>

=== khanalAjit/GiftcardShop-XML/catalog_20048817.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="catalog_20048817.css" type="text/css"?>

<!--
    Author : Ajit Khanal
    Date : 03/31/2022
-->
<!-- connecting to the schema-->
<ajstore xsi:noNamespaceSchemaLocation="catalog_20048817.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <heading>
        <logo of="store"/>  <!--Using attribute for recognition and CSS-->
        <middlef>
            <store_name>AJStore</store_name>
            <contact_info>
                <website> www.AJStores.com</website>
                <address> Address : Kageshwori Manohara-7 </address>
                <mobile_phone>9818943327</mobile_phone>
                <telephone>01555555</telephone>
            </contact_info>
        </middlef>
        <rightf>
            <social_medias>
                Find Us At:
                <facebook>AJStore
                    <flogo></flogo>
                </facebook>
                <instagram>it's_AJStore
                    <ilogo></ilogo>
                </instagram>
                <twitter>AJStore
                    <tlogo></tlogo>
                </twitter>
     
            </social_medias>
        </rightf> 
    </heading>
   
    <!-- welcoming the visitor to the store-->
    <welcome>
        Welcome to the AJStore.
    </welcome>

    <!-- listing the available giftcards-->
    <giftcards>
        <card CID="C1" type="digital">
            <design>    <!-- design,fleft(flex left), and fright(flex right) are for css use-->
                <fleft>
                    <image name="amazon"> </image>
                    <name> Amazon Gift Card</name>
                </fleft>
                <fright>
            <!-- code number is optional-->
                    <type> Digital Giftcard </type>
                    <country>Country = United Kingdom</country>
                    <code_number>Code Number = 01NP6C5</code_number>
                    <cost currency="dollar">Price = $50</cost>
                    <availability>In Stock</availability>
                    <validity> Valid Until = Always Valid</validity>
            <!-- discount is optional-->
                    <discount specialEvent="Festivals"> 15% off in any purchase on amazon during festivals.</discount>
                    <quantity>No. Of Cards Available = 25</quantity>
                    <!-- details of the card is written in description-->
                    <description>
                        <![CDATA[ This Amazon gift card is a card pre-loaded with $50 and will be 
                        sent out via email, post, or another method to the buyer. The buyer can redeem 
                        their gift card on Amazon for anything on Amazon. They can purchase gift cards up to $10,000 
                        in a single day]]>
                    </description>
                </fright>
            </design>
            <reviews>
                Here's what people think about this card.
                <recommendations> Recommended by 1K+ people </recommendations>
                <rating> Rating: 4.5</rating>
            </reviews>
        </card>


        <card CID="C2" type="physical">
            <design>
                <fleft>
                    <image name="kalyan"> </image>
                    <name> Kalyan Gold Jewellery Gift Card</name>
                </fleft>
                <fright>
                    <type> Physical Giftcard</type>
                    <country>Country = India</country>
                    <cost currency="USD">Price = $5</cost>
                    <availability> In Stock</availability>
                    <discount> 5% discount on HSBC Cashback Card Transactions. </discount>
                    <quantity>No. Of Cards Available = 30</quantity>
                    <description>
                        <![CDATA[ This Kalyan gift card is a physical gift card worth $5 and can be used
                        to buy any products in Kalyan Jewellaries. There is a 5% discount on HSBC 
                        Cash back Card Transactions. ]]>
                    </description>
                </fright>
            </design>
            <!-- product details is optional-->
            <product_details>
                Physical Structures of the Card
                <card_size cardType="Plastic">
                    <dimention> Dimention = 15.01 x 11 x 0.05 cm </dimention>
                    <weight> Weight = 50 Grams </weight>
                </card_size>
                <manufacturer> Manufactured By = Kalyan </manufacturer>
                <selling_rank> #324 in top selling giftcards.</selling_rank>
            </product_details>
        </card>

        <card CID="C3" type="physical">
            <design>
                <fleft>
                    <image name="lifestyle"> </image>
                    <name> Lifestyle Gift Card</name>
                </fleft>
                <fright>
                    <type>Physical Giftcard</type>
                    <country>Country = India</country>
                    <cost currency="USD">Price = $20</cost>
                    <availability>In Stock</availability>
                    <discount> 5% discount on HSBC Cashback Card Transactions. </discount>
                    <quantity>No. Of Cards Available = 30</quantity>
                    <shipping_charge facility="special">Shipping Charge = $5</shipping_charge>
                    <description>
                        <![CDATA[This Lifestyle gift card is a physical gift card worth $20 and can be used
                        to buy any products sold by Lifestyle enterprises. There is a 5% discount on HSBC 
                        Cash back Card Transactions. There is also a special shipping facility which delivers
                        this card to the doorstep of the buyer. ]]>
                    </description>
                </fright>
            </design>
                    <!-- optional-->
            <product_details>
                Physical Structures of this card
                <card_size cardType="paper">
                    <dimention> Dimention = 25.2 x 12 x 0.6 cm </dimention>
                    <weight> Weight = 50 Grams </weight>
                </card_size>
                <manufacturer>Manufactured By = Lifestyle </manufacturer>
                <selling_rank> #320 in top selling giftcards.</selling_rank>
            </product_details>
        </card>

        <card CID="C4" type="digital">
            <design>
                <fleft>
                    <image name="iTunes"> </image>
                    <name> iTunes Gift Card</name>
                </fleft>
                <fright>
                    <type>Digital Giftcard</type>
                    <country> Country = USA</country>
                    <!-- code number is optional-->
                    <code_number>Secret Code = 524896E</code_number>
                    <cost currency="USD">Price = $50</cost>
                    <availability>In Stock</availability>
                    <validity>Valid Until = 30/12/2025 </validity>
                    <!-- discount is optional-->
                    <quantity>No. Of Card Available = 15</quantity>
                    <description>
                        <![CDATA[ An iTunes gift card (usually labeled as an App Store & iTunes card) is 
                        pre-purchased credit for Apple's various digital services. This includes the 
                        iTunes Storeâ€”Apple's media and software marketplace where you can buy music, 
                        movies, apps, and more. The available giftcard is a digital card worth $50]]>
                    </description>
                </fright>
            </design>
            <!-- review is also optional-->
            <reviews>
                Comments
                <comments cmntBy="uid100">Rakh: Awsome Product! </comments>
                <comments cmntBy="uid103">Rakesh: I Love the Store. </comments>
            </reviews>
        </card>

    </giftcards>

    <!-- ending is used for css-->
    <!-- giftcard providers and their company logo are displayed at the end-->
    <ending>
        Our Giftcard Partners
        <amazon>
            <logo of="amazon"></logo>
            Amazon
        </amazon>
        <kalyan>
            <logo of="kalyan"></logo>
            Kalyan Jwellers
        </kalyan>
        <lifestyle>
            <logo of="lifestyle"></logo>
            Lifestyle
        </lifestyle>
        <itunes>
            <logo of="iTunes"></logo>
            iTunes
        </itunes>
    </ending>


</ajstore>
